id: I4E3F4254
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T11:17:57+00:00'
last_modified: '2022-06-08T12:00:09.201591+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC282
  title: ཟློས་གར་པད་མའི་དགའ་ཚལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '6464':
      image_group_id: I2PD18338
      title: ''
      total_pages: 296
      order: 1
      base_file: 6464.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
